#!/bin/bash

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <YouTube URL>"
  exit 1
fi

youtube_url="$1"
cropped_url=$(echo "${youtube_url}" | sed -E 's/^.*(v=|\/)([^&?]+).*$/https:\/\/youtu.be\/\2/')
echo "${cropped_url}"
