
############
# SETTINGS #
############

# Enable mouse and set history
set -g mouse on
set -g history-limit 50000

# Status line
set -g status-style 'bg=#333333 fg=#7777ad'
set -g status-interval 2
set -g status-left-length 60
set -g status-right-length 80
set -g status-right "%H:%M %d-%b-%y"'#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)'

# Other styles
set -ag message-style 'bg=black fg=yellow'
set -g pane-border-style 'bg=#333333 fg=#7777ad'
set -g pane-active-border-style 'bg=#7777ad fg=#333333'


############
# KEYBINDS #
############

# Set C-a prefix alongside C-b
set -g prefix2 C-a
bind C-a send-prefix

# Enter vi-mode (to scroll up/down, etc)
bind v copy-mode

# Split panes -- Alt+key
unbind %
unbind '"'
bind M-l split-window -h
bind M-j split-window -v

# Switch panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Resize panes
bind -r K resize-pane -U
bind -r J resize-pane -D
bind -r H resize-pane -L
bind -r L resize-pane -R

# Pane swapping
bind-key E swap-pane -D         # mover hacia abajo/derecha

